---
- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present
    update_cache: yes

- name: Start and enable PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes
