---
- name: Configure web and db servers
  hosts: all
  become: yes
  roles:
    - common

- name: Configure web server
  hosts: web
  become: yes
  roles:
    - web

- name: Configure db server
  hosts: db
  become: yes
  roles:
    - db
